# Built with Jekyll 3.2.0

# Setup
title:               Shakespeare's Sonnets
tagline:             'Even jekyll cannot hide this beauty'
description:         'An example of using Ed for Poems'
url:                 'http://chads.space'
baseurl:             '/sonnets'

# About/contact
author:
  name:              Chad Nelson
  url:               https://twitter.com/bibliotechy
  email:             chadbnelson@gmail.com

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


